### ISSUE TITLE
"Server Info" button crashes game - now the world crashes on load

### ISSUE THREAD

**Issue by obuw** [LatvianModder/FTBUtilities#294]
In my SSP world I accidentally clicked the "Server Info" button from FTBUtils while in the inventory screen and my game crashed. Now it is crashing every time I load the world.

[Crash Log](http://pastebin.com/9q0ju4kw)

I created a new world to test this and got the same result, 100% reproducible.

Removed FTBUtilities and the game still crashes on world load.

FTBUtilities 1.10.2-3.1.4
FTBLib 1.10.2-3.1.5
Modpack: Direwolf20 1.10 1.1.1 - 1.1.3

**Comment by LatvianModder** [comment]
I have already fixed this issue, wait for pack update. Meanwhile, you can remove FTBU/FTBL from mods folder

**Comment by obuw** [comment]
I have just updated to the latest FTBUtils & FTBLib (3.2.1) and my game is still crashing on world load.

Removing the mods from the folder does not help either.

Perhaps I need to edit a file in the save directory or change a config setting of some kind?
