### ISSUE TITLE
/home not working properly - sends you to a spawn, or last slept bed at times

### ISSUE THREAD

**Issue by rob5251** [LatvianModder/FTBUtilities#51]
There seems to be an issue occurring with _/home set_. I do _/home set homename_ but when I actually try to _/home_ to that home then it sends me to a location near spawn instead.

This has happend for a couple of people on my server, sometimes it will set properly though.

Edit:
I turned off forge's spawn fuzz and doing /home will send you to exact spawn location, if fuzz is on it just sends you to an area within the spawn fuzz (but always the same spot).

**Comment by LatvianModder** [comment]
That was fixed in 1.0.17.x for 1.7.10

**Comment by rob5251** [comment]
It's still happening for me and I'm on versions:
FTB Utilities 1.7.10 - 1.0.17.1
FTB Lib 1.7.10 - 1.0.17.2

All config files were generated using those versions.

**Comment by LatvianModder** [comment]
Hm. If you are an admin, can you try /warp, /admin setwarp, /admin delwarp for me? It could be that /home command is just derpy

**Comment by rob5251** [comment]
I've managed to set up a warp without any issues as of yet.

**Comment by LatvianModder** [comment]
Must be the home command itself then

**Comment by kwpugh** [comment]
I'm experiencing the same behavior with /home on my server running 1.0.17.3 of utils and lib.

**Comment by LatvianModder** [comment]
Ah, got it. It seems like its setting to player's position, but not clones his position but keeps tracking it, because the position is the same Java object. Will be fixed in FTBUtilities 1.0.17.5

**Comment by rob5251** [comment]
Nice, looking forward to seeing this fixed. :+1:

**Comment by LatvianModder** [comment]
http://minecraft.curseforge.com/projects/ftb-utilities/files/2283436

**Comment by kwpugh** [comment]
Thank you taking care of this.  Greatly appreciated.

**Comment by Fearzu** [comment]
Still happening in Infinity Evolved 2.4.2, FTB Utilities 1.0.17.6

**Comment by KIN0025** [comment]
This seems to still be an issue in the 1.8.9 releases - any chance of a fix?

**Comment by minimeistro** [comment]
Still having this exact issue in 1.0.11.3 ://. Can homes be outright diabled by setting "home": to false in config.json? So I can use the home command from an alternate mod

**Comment by LatvianModder** [comment]
Not sure, this is 1.7.10, long since unsupported

**Comment by mr-blaack** [comment]
please fix it

**Comment by Jwely** [comment]
Spun up a server for some friends, they too are experiencing this issue where previously set homes just send them right back to spawn, using most recent 1.7.10 version with FTB Infinity Evolved. Any idea what's causing this?

**Comment by nikitinalexx** [comment]
That should be a very bad developer, who throughout tens of versions every time says it is fixed while it is not.

**Comment by ktccd0** [comment]
This is still an issue as of 1.7.10

**Comment by Hillgrove** [comment]
yup... still not fixed and Dev has copped out by saying 1.7.10 is dead... .lol
