### ISSUE TITLE
Crash on turning on RFTools Builder

### ISSUE THREAD

**Issue by neoc666** [LatvianModder/FTBUtilities#702]
McJty referred me to FTBUtilities https://github.com/McJty/RFTools/issues/1720#issuecomment-384385681

FTBUtilities-5.0.0.11

Description from there:

This only happens occasionally, I have no clue what causes it.

Using a Builder with Fortune Quarry (non-clearing) and filter for several blocks. y = 2 (bedrock) to 64 inclusive, x/z exact chunks (2), all in all 16 x 32 x 63=32256 blocks (I think it crashed with larger quarries in the past). When turning on with a lever in the past, now via switching redstone setting to ignore, then clicking the Y-level/restart button to actually start, I immediately crash.

FTBRevelation-1.8.0-1.12.2 with a lot of mods disabled. No OptiFine.

I'm pretty sure this also happened with the (almost) vanilla FTBRevelation-1.8.0, so it is unlikely to be caused by changes made by me.

minecraft 1.12.2
forge-1.12.2-14.23.2.2627
mcjtylib-1.12-2.6.7
rftools-1.12-7.32

Crash log:
https://github.com/McJty/RFTools/files/1948296/2018-04-25-1.zip

**Comment by josephcsible** [comment]
I've seen this crash a lot: McJty/RFTools#1686, McJty/RFTools#1699. However, I haven't been able to reproduce it myself. I posted some troubleshooting steps at https://github.com/McJty/RFTools/issues/1686#issuecomment-375905400 but nobody ever followed them.

**Comment by neoc666** [comment]
I could try to narrow it down by making the quarry card dimensions smaller and smaller until I find the block which causes it. Can you provide more info on what seems to trigger the block? Something like checking permissions? So there would be a block that has permissions? Maybe even the bedrock?

**Comment by josephcsible** [comment]
I don't think the issue is with a given block. Instead, can you try the troubleshooting steps I linked to (but substitute "builder" for "elevator")?

**Comment by neoc666** [comment]
Is the following the relevant stack trace?

> ServerUtils.isOP
> Ranks.getRank
> FTBUPermissionHandler.hasPermission
> PermissionAPI.hasPermission
> FTBUtilitiesPermissions.canModifyBlock
> ClaimedChunks.canPlayerInteract
> FTBUPlayerEventHandler.onBlockBreak

It starts with trying to break a block, checks if I am allowed to do so, checks my "rank", whatever that is. I'm playing single player without any special server involved. Maybe the rank check relies on data pulled from the internet and that initially when wrong (I saw some log entries trying to connect to the internet and failing).

Only claimed and loaded chunks involved are the one in which the builder is, and that one is not within the bounds of the quarry.

**Comment by josephcsible** [comment]
You're correct, but unfortunately that's not helpful to fix this. Please try to answer the 4 troubleshooting questions in the post I linked to above.

**Comment by neoc666** [comment]
1. is not applicable
2. the crash is sporadic
3. see 2
4. no changes to FTB Utils, everything is on default, chunkloading already explained above

One curious thing I also noticed: The crash always only happens immediately after starting the builder; once I reloaded my world, the builder continues to run without any further crashes.

**Comment by LatvianModder** [comment]
This was already fixed in my mod some time ago

**Comment by iHeartZigg** [comment]
Just popping in to mention that the error is still occurring in the latest version of both mods.

Here's my entire log from the session, you'll find the error/crash from line 12324. 
[latest.log](https://github.com/LatvianModder/FTBUtilities/files/1977722/latest.log)

**Comment by neoc666** [comment]
I can confirm that it still happens. But it only happened once to me since the fixes, I'd guess it's a lot rarer now.

**Comment by iHeartZigg** [comment]
As far as I can tell, the issue is produced by the builder attempting to break a block while you save and quit (OR loading!) 

To reproduce, simply save and quit while the builder is breaking blocks.

**Comment by LatvianModder** [comment]
Commented on RFTools issue

**Comment by josephcsible** [comment]
For anyone following this issue but not the RFTools one, I just uploaded a test build there that might fix this.
